Update signature.rs to use OffsetDateTime
Fixes the following deprecation warning:

```
error: use of deprecated item 'time::primitive_date_time::PrimitiveDateTime::now': This method returns a value that assumes an offset of UTC.
   --> rusoto/signature/src/signature.rs:277:28
    |
277 |         let current_time = PrimitiveDateTime::now();
    |                            ^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> rusoto/signature/src/lib.rs:11:45
    |
11  | #![cfg_attr(not(feature = "unstable"), deny(warnings))]
    |                                             ^^^^^^^^
    = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error: use of deprecated item 'time::primitive_date_time::PrimitiveDateTime::now': This method returns a value that assumes an offset of UTC.
   --> rusoto/signature/src/signature.rs:442:20
    |
442 |         let date = PrimitiveDateTime::now();
    |                    ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

OffsetDateTime::now() explicitly assumes UTC, so behavior should be
equivalent (only ran `make unit_test` however).